## Introduction to NumPy

NumPy (Numerical Python) is a fundamental package for scientific computing with Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures. In this notebook, we will cover some basic NumPy commands and concepts.

### Importing NumPy

To get started, we need to import the NumPy library. Typically, it's imported with the alias `np` for convenience:


In [1]:
import numpy as np

Creating NumPy Arrays
1. Creating arrays from Python lists
You can create a NumPy array from a Python list:

In [2]:
# Creating a 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array (matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Display the arrays
print("1D Array:")
print(arr1d)
print("2D Array:")
print(arr2d)

1D Array:
[1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]


2. Creating arrays from Python lists


In [3]:
# Creating an array of zeros
zeros_array = np.zeros((3, 3))

# Creating an array of ones
ones_array = np.ones((2, 4))

# Creating an array of evenly spaced values
range_array = np.arange(0, 10, 2)  # Start, Stop (exclusive), Step

# Creating an array of evenly spaced values with a specific number of elements
linspace_array = np.linspace(0, 1, 5)  # Start, Stop, Number of Elements

# Display the arrays
print("Zeros Array:")
print(zeros_array)
print("Ones Array:")
print(ones_array)
print("Range Array:")
print(range_array)
print("Linspace Array:")
print(linspace_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range Array:
[0 2 4 6 8]
Linspace Array:
[0.   0.25 0.5  0.75 1.  ]


## Array Attributes and Operations
NumPy arrays come with several attributes, such as `shape`, `dtype`, and various mathematical operations:

In [4]:
# Attributes of an array
shape = arr2d.shape
dtype = arr2d.dtype

# Mathematical operations
sum_result = arr1d + arr1d
product_result = arr1d * 2

# Display the attributes and results
print("Shape:", shape)
print("Data Type:", dtype)
print("Sum of arr1d:", sum_result)
print("Product of arr1d:", product_result)

Shape: (2, 3)
Data Type: int64
Sum of arr1d: [ 2  4  6  8 10]
Product of arr1d: [ 2  4  6  8 10]
